name: Deploy android library

on:
  push:
    branches: [ main ]

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  
      - name: "Bootstrap Workspace"
        run: flutter packages get
      - name: "Generate library"
        run: | 
          flutter build aar 
          cp publish.gradle .android/app/
          cd .android
          { head -n 3 app/build.gradle; echo "apply from: 'publish.gradle'"; tail -n +4 app/build.gradle; } > app/generated_build.gradle
          rm app/build.gradle
          mv app/generated_build.gradle app/build.gradle
          gradle publish
        env:
          ACTION_USER_ID: ${{ secrets.PERSONAL_USER_ID }}   
          ACTION_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}   
